import './global.css'
import TrpcProvider from "@/src/lib/trpc/Provider"
import NextAuthProvider from "@/src/lib/auth/Provider"

export const metadata = {
  title: 'Welcome to chart-explorer',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TrpcProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </TrpcProvider>
      </body>
    </html>
  )
}
